name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-windows:
    runs-on: linux-latest
    defaults:
      run:
        working-directory: ./${{ matrix.app }}
    strategy:
      matrix:
        app: [kusudamaSample, itemHolder]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build installDist
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest-linux
        prerelease: true
        title: EWBIK Linux
        files: |
          ewbik-linux.zip

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./${{ matrix.app }}
    strategy:
      matrix:
        app: [kusudamaSample, itemHolder]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build installDist
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest-windows
        prerelease: true
        title: EWBIK Windows
        files: |
          ewbik-windows.zip
