name: Build Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Gradle
      working-directory: ./itemHolder
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build installDist
    - name: Build with Gradle
      working-directory: ./kusadamaSample
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build installDist
    - name: Copy licenses
      run: |
        cp LICENSE ./itemHolder/build/install/
        cp LICENSE ./kusadamaSample/build/install/
      shell: bash
    - uses: papeloto/action-zip@v1
      with:
        files: 
        - ./itemHolder/build/install/
        - ./kusadamaSample/build/install/
        recursive: false
        dest: ewbik-linux.zip
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest-linux
        prerelease: true
        title: EWBIK Linux
        files: |
          ewbik-linux.zip
